### ISSUE TITLE
Change help text for amp_pages

### ISSUE THREAD

**Issue by balazs-endresz** [coderedcorp/wagtail-seo#1]
The help text currently says: `Generates an alternate AMP version of article pages that are preferred by search engines. See https://amp.dev/`

But AMP is no longer required for top stories: https://www.searchenginejournal.com/googles-top-stories-to-show-more-than-just-amp-pages/370792/

So, would it make sense to remove the part about amp being `preferred by search engines`? AFAIK now it shouldn't directly affect ranking either. And like most developers I'd rather not encourage people to use it.

Also, this option doesn't seem to actually generate an AMP page, only a link to one, so the first half of the help text seems incorrect as well.

**Comment by vsalvino** [comment]
Good catch, the AMP page itself is still a work in progress and not currently implemented. See: https://github.com/coderedcorp/wagtail-seo/pull/2. Once the package is ready for production use we will signify with 1.0 version number.

Regarding your thoughts on necessity of AMP... That is great news that AMP will no longer be a *requirement*, however I don't know if that means it will also not be *preferred*. I know Google engages in some dark patterns of ranking AMP pages above non-AMP pages in search results, even when showing both (in the name of "speed").

At any rate, AMP is something that will inevitably require additional conscious development from the website owner (i.e. adding special AMP CSS and templates)... we can only do so much "magic" out of the box. So it might be better to turn this feature off by default, especially in light of the fact that it will not longer be required for top stories.

Thoughts?

**Comment by balazs-endresz** [comment]
Yeah, it might be still preferred in rankings, and to be more precise, I just haven't heard google say anything about that recently. But I don't really have any more insight on this.

I'd definitely suggest disabling all AMP related features by default and at least being more neutral about the wording because things can always change and it has _so many_ downsides too.

**Comment by vsalvino** [comment]
I was also debating including AMP stuff in this package. But decided it would make sense to do so, as the *only* reason people use AMP is to please the Google gods; website visitors do not actually benefit from it (similar to other metadata). So figured it made sense to include it here and be done with it.

I think the AMP setting could be off by default, and include help text indicating that this setting is geared towards article/blog-heavy sites, with a disclaimer about "allow Google to distribute your website content on your behalf. May improve search rankings but reduce actual number of visitors to your website". Unfortunately AMP is hard to explain to non-developers. Any suggestions would be appreciated!

**Comment by balazs-endresz** [comment]
For a shorter help text I'd rather go with something generic: `Before you enable AMP make sure you understand what it might help with and its disadvantages too.` But what you mentioned makes sense too.

**Comment by vsalvino** [comment]
We will be removing AMP support. See #21
