### ISSUE TITLE
'NoneType' object has no attribute 'get_full_name' 

### ISSUE THREAD

**Issue by anefta** [coderedcorp/wagtail-seo#10]
Hi,

I followed this wagtail-seo tutorial: https://docs.coderedcorp.com/wagtail-seo/getting-started/install.html  but I get **'NoneType' object has no attribute 'get_full_name'** 
![wagtail-seo-error](https://user-images.githubusercontent.com/74997108/100171969-fb0d6880-2ecf-11eb-9241-f6e9ad273d4f.png)

**Comment by vsalvino** [comment]
That comes from `SeoMixin.seo_author` property.

This assumes your Wagtail page owner is a user mode based on Django's AbstractUser model (which is generally a best practice). Under "normal" circumstances this should work... if you are using a totally custom user model then you might need to override `seo_author` to return something else.

Wagtail page owner: https://github.com/wagtail/wagtail/blob/fe427efb756db18dd0babf43c09665ef4a05f2a1/wagtail/core/models.py#L751

Django user model: https://github.com/django/django/blob/b9fd09d21b722c3745501151f9cbd5b95ccc3177/django/contrib/auth/models.py#L373

In your case... it appears the page does not have an owner. I am wondering how this is possible, if the page was possibly created programmatically? I suppose we should handle this edge case and return a None or blank if the page has no owner.

**Comment by anefta** [comment]
Hi,
Yes, I was trying to create pages programmatically, so return a None or blank if the page has no owner would work I guess.

**Comment by vsalvino** [comment]
Fixed in main branch, for 0.0.3
