### ISSUE TITLE
Shouldn't `canonical_url` have `null=True`?

### ISSUE THREAD

**Issue by janbaykara** [coderedcorp/wagtail-seo#12]
I'm getting non-null errors for this in production. Is there a reason why this is not nullable?

**Comment by vsalvino** [comment]
Absolutely, it should allow null/blank, and if so, generate the canonical URL from the page URL as usual.

**Comment by janbaykara** [comment]
I can't unfortunately but it occurred after saving a draft of a SEOMixin'd wagtail page; the logs at the time said that `canonical_url` couldn't be set to `Null`. I fixed this issue locally by overriding the model field to allow `Null`.

**Comment by vsalvino** [comment]
Canonical URL should not have null=True per explanation above. In this case, the validation is working correctly by failing when trying to set null. Flee free to re-open if new information arises.
