### ISSUE TITLE
og:image problem

### ISSUE THREAD

**Issue by basitiyidir** [coderedcorp/wagtail-seo#13]
Hello there,

How can I solve this.

It writes the domain name at the beginning of the url.

`<meta property="og:image" content="https://domain.comhttps://d309hejw083trb.cloudfront.net/media/public/images/travel.jpg" />`

It should be like this

`<meta property="og:image" content="https://d309hejw083trb.cloudfront.net/media/public/images/travel.jpg" />`

The site's pictures come from cdn.

Thanks for help

**Comment by vsalvino** [comment]
This was fixed in main branch by #11
