### ISSUE TITLE
The twitter:description metatag is missing

### ISSUE THREAD

**Issue by besarbertasholli** [coderedcorp/wagtail-seo#38]
The twitter:description metatag is missing (falls back to description)

Error is reported on Social Share Preview web app also.
Check the [URL](https://socialsharepreview.com/?url=https://www.coderedcorp.com/) included.

**Comment by vsalvino** [comment]
I believe this is an optional tag, per [twitter specs](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image). However there is a pull request #18 in place for this.

**Comment by vsalvino** [comment]
Closed by #18
