### ISSUE TITLE
Wagtail 4.0

### ISSUE THREAD

**Issue by Elrigor** [coderedcorp/wagtail-seo#42]
Hi mate!

I was trying to use it with the newest version of wagtail, the  4.0 one, but I couldn't.

Will it have support for it?

Thanks!

**Comment by vsalvino** [comment]
We have not tested it with 4.0 yet. Will try to get support added this week!

**Comment by dustinblanchard** [comment]
Any updates here?

**Comment by janbaykara** [comment]
Very keen to see this project update for Wagtail 4. Will test it out.

**Comment by vsalvino** [comment]
Fixed via #45
