### ISSUE TITLE
Confusing struct_org_logo help text

### ISSUE THREAD

**Issue by Chadys** [coderedcorp/wagtail-seo#59]
In `struct_org_logo`, the help text is "Leave blank to use the logo in Settings > Layout > Logo".
But I don't see any Layout settings nor any mechanism for the `seo_logo` getter to use a fallback image

**Comment by vsalvino** [comment]
Good catch. This package was original built-in to our other package `coderedcms`, and split out sometime in 2018/2019. I think that help text is a holdover from that.

The help text should be removed as the developer will need to choose the default logo when implementing it on their site.

**Comment by Chadys** [comment]
I can propose the following help text, using the google organizational data struct definition constraints:
`"Logo representative of the organisation. Must be 112x112px minimum;  take note that it will be displayed on a white background"`

**Comment by vsalvino** [comment]
Sounds good to me!
