### ISSUE TITLE
Add simplified mixin without struct information

### ISSUE THREAD

**Issue by Chadys** [coderedcorp/wagtail-seo#60]
Since struct informations should only be put in the homepage(s), it seems a bit wasteful to have all those struct fields on every pages. What I propose:
- Create a `SeoSimpleMixin` (name subject to debate), which does not contain any struct fields and use only `seo_meta_panels` and `seo_menu_panels` as `seo_panels`
- Update the docs to indicate to use this new mixin on non-root pages and to only add `{% include "wagtailseo/struct_data.html" %}` to the template of pages using `SeoMixin` (root pages)

I would be willing to make the PR for this.

**Comment by vsalvino** [comment]
I have been thinking the same thing recently. The original reason for this was if you a franchise store website, each location page would need to have its own structured data for location. But that scenario can easily be accounted for with the mixin. Alternatively, it might make even more sense as a site setting. If you want to make a pull request, that would be awesome!

Here's what I'm thinking:
* `SeoMixin` can continue to be the primary mixin, just remove the structured data fields.
* `SeoOrgMixin` (or `SeoSettings`) could probably contain all the structured data fields.
* `SeoMixin` should probably continue to have the logic / utility methods to handle structured data. Basically it will need to check if the current model has those fields, if not, look on the page's Root Page (or the site settings if we go that route).

**Comment by Chadys** [comment]
While I agree that a Site settings would make more sense to store struct information, wouldn't changing the `SeoMixin` be a breaking change for your current users? Even while keeping utility methods, data migration could be hard depending on how the class was used.
And if a breaking change is done, it doesn't make much sense for me to keep the logic and not the data of structured data in `SeoMixin`, it make it harder to understand the class. It seems more natural to keep utility class grouped with its data, either as methods of `SeoOrgMixin` or `SeoSettings`.
That's why I proposed to rename to `SeoSimpleMixin` without touching the current existing `SeoMixin` class.
What do you think :)?

**Comment by Chadys** [comment]
As a sidenote, changing from a mixin to a setting model would make it possible to easily override the class to default `struct_org_logo` to another global logo site setting (reference to #59 ) in case there is already one such settings

**Comment by Chadys** [comment]
Let me try a PR :)
