### ISSUE TITLE
doc: articles metadata forget necessary step

### ISSUE THREAD

**Issue by Chadys** [coderedcorp/wagtail-seo#62]
In the [Articles paragraph of the documentation](https://docs.coderedcorp.com/wagtail-seo/getting-started/edit-meta.html#articles), there is the following mention:
> No additional action is required to enable article markup.

Which is not true, since for article metadata to be enabled, we need to set `seo_content_type = SeoType.ARTICLE` on the page. This is correctly specified in the [Installation page](https://docs.coderedcorp.com/wagtail-seo/getting-started/install.html#install-wagtail-seo)

**Comment by vsalvino** [comment]
You're on a roll! Pull request welcome :)
