### ISSUE TITLE
'wagtailsettings' is not a registered namespace

### ISSUE THREAD

**Issue by janbaykara** [coderedcorp/wagtail-seo#8]
It looks like `wagtail.contrib.settings` is also required in `INSTALLED_APPS` for this app to run, but that's not mentioned in the [Getting Started](https://docs.coderedcorp.com/wagtail-seo/getting-started/install.html) guide.

**Comment by morenoh149** [comment]
@janbaykara that's a pretty easy PR to submit

**Comment by vsalvino** [comment]
Good catch... this app is still in early stages so any bug fixes or PRs are appreciated.

**Comment by janbaykara** [comment]
> @janbaykara that's a pretty easy PR to submit. https://github.com/coderedcorp/wagtail-seo/blob/main/docs/getting-started/install.rst

Yep that's true. I was in a rush at the time of posting! PR submitted.

**Comment by vsalvino** [comment]
Fix via #9
